[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_extra_dirs = 
    /Users/csanz/Documents/Arduino/libraries
lib_deps =
    bblanchon/ArduinoJson
build_flags = 
    -D IOTCLOUD_ENABLE_PRESENCE_SENSOR
