; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = nodemcuv2
extra_configs = ../common_env.ini

[env:nodemcuv2]
lib_deps = 
	${nodemcuv2_base.lib_deps}
	adafruit/Adafruit GFX Library@^1.12.4
	adafruit/Adafruit SSD1306@^2.5.16
model_num = THERMOSTAT_SUBSENSOR
version = v1.1.1
build_flags = 
	-D IOTCLOUD_ENABLE_SI7021
	-D IOTCLOUD_ENABLE_THERMOSTAT

extends = nodemcuv2_base, ota_template