[platformio]
default_envs = nodemcuv2
extra_configs = ../common_env.ini

[env:nodemcuv2]
lib_deps =
    ${nodemcuv2_base.lib_deps}
model_num = WASHING_MACHINE
version = v1.1.0
build_flags = 
    -D IOTCLOUD_ENABLE_NOTIFIER
    -D IOTCLOUD_ENABLE_SERVO

extends = nodemcuv2_base, ota_template