[platformio]
default_envs = nodemcuv2
extra_configs = ../common_env.ini

[env:nodemcuv2]
extends = nodemcuv2_base
lib_deps =
    ${nodemcuv2_base.lib_deps}
build_flags = 
    -D IOTCLOUD_ENABLE_SI7021
    -D IOTCLOUD_ENABLE_WIFI_RSSI

